//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrojanShell.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrojanShell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] abp_js {
            get {
                object obj = ResourceManager.GetObject("abp_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   # translation for Simplified Chinese
        ///
        ///TrojanShell=木马壳
        ///
        ///# Menu items
        ///Enable System Proxy=启用系统代理
        ///Mode=系统代理模式
        ///PAC=PAC模式
        ///Global=全局模式
        ///Servers=服务器
        ///Edit Servers...=编辑服务器...
        ///Share Server Config...=分享服务器配置...
        ///Scan QRCode from Screen...=扫描屏幕上的二维码...
        ///Import URL from Clipboard...=从剪贴板导入URL...
        ///Local PAC=使用本地 PAC
        ///Online PAC=使用在线 PAC
        ///Edit Local PAC File...=编辑本地 PAC 文件...
        ///Update Local PAC from GFWList=从 GFWList 更新本地 PAC
        ///Edit User Rule for GFWList...=编辑 GFWList 的用户规则...
        ///Copy Local PAC URL=复制本地 PAC 网址
        ///Sta [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cn {
            get {
                return ResourceManager.GetString("cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon horse {
            get {
                object obj = ResourceManager.GetObject("horse", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   listen-address __PRIVOXY_BIND_IP__:__PRIVOXY_BIND_PORT__
        ///toggle 0
        ///logfile TrojanShell_Privoxy.log
        ///show-on-task-bar 0
        ///activity-animation 0
        ///forward-socks5 / __SOCKS_HOST__:__SOCKS_PORT__ .
        ///max-client-connections 2048
        ///hide-console
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string privoxy_conf {
            get {
                return ResourceManager.GetString("privoxy_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] privoxy_exe {
            get {
                object obj = ResourceManager.GetObject("privoxy_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] proxy_pac_txt {
            get {
                object obj = ResourceManager.GetObject("proxy_pac_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap T18 {
            get {
                object obj = ResourceManager.GetObject("T18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap T24 {
            get {
                object obj = ResourceManager.GetObject("T24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap T48 {
            get {
                object obj = ResourceManager.GetObject("T48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   # translation for Simplified Chinese
        ///
        ///TrojanShell=木马壳
        ///
        ///# Menu items
        ///Enable System Proxy=启用系统代理
        ///Mode=系统代理模式
        ///PAC=PAC模式
        ///Global=全局模式
        ///Servers=服务器
        ///Edit Servers...=编辑服务器...
        ///Share Server Config...=分享服务器配置...
        ///Scan QRCode from Screen...=扫描屏幕上的二维码...
        ///Import URL from Clipboard...=从剪贴板导入URL...
        ///Local PAC=使用本地 PAC
        ///Online PAC=使用在线 PAC
        ///Edit Local PAC File...=编辑本地 PAC 文件...
        ///Update Local PAC from GFWList=从 GFWList 更新本地 PAC
        ///Edit User Rule for GFWList...=编辑 GFWList 的用户规则...
        ///Copy Local PAC URL=复制本地 PAC 网址
        ///Sta [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tc {
            get {
                return ResourceManager.GetString("tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ! Put user rules line by line in this file.
        ///! See https://adblockplus.org/en/filter-cheatsheet
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string user_rule {
            get {
                return ResourceManager.GetString("user_rule", resourceCulture);
            }
        }
    }
}
